- name: Create /home/vagrant/scripts folder
  file:
    path: /home/vagrant/scripts
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Copy capture_input.sh from files
  copy:
    src: "{{ capture_input_script }}"
    dest: /home/vagrant/scripts/capture_input.sh
    owner: vagrant
    group: vagrant
    mode: '0775'

- name: Copy my_script.sh from files
  copy:
    src: "{{ my_script }}"
    dest: /home/vagrant/scripts/my_script.sh
    owner: vagrant
    group: vagrant
    mode: '0775'

- name: Copy hello_loop.sh from files
  copy:
    src: "{{ hello_loop_script }}"
    dest: /home/vagrant/scripts/hello_loop.sh
    owner: vagrant
    group: vagrant
    mode: '0775'

- name: Copy if_statement.sh from files
  copy:
    src: "{{ if_statement_script }}"
    dest: /home/vagrant/scripts/if_statement.sh
    owner: vagrant
    group: vagrant
    mode: '0775'

- name: Copy basic_function.sh from files
  copy:
    src: "{{ basic_function_script }}"
    dest: /home/vagrant/scripts/basic_function.sh
    owner: vagrant
    group: vagrant
    mode: '0775'
